/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZPgUkY3HY5r
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"


export function comp() {
  return (
    <div className="flex flex-col w-full items-center gap-4 pt-8">
      <div className="flex flex-col w-full items-center gap-2">
        <div className="w-full max-w-lg flex flex-col items-center gap-2 text-center">
          <h1 className="text-3xl font-bold tracking-tight">create an Image</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter a prompt to generate an image.</p>
        </div>

        <div className="w-full max-w-sm flex flex-col items-center gap-2">
          <Input className="w-full" placeholder="Enter a prompt" type="text" />
          
          <Button className="w-full max-w-xs">Generate</Button>
        </div>
      </div>
      <div className="flex w-full max-w-lg justify-center items-center gap-4 py-4">
        <img
          alt="Generated Image"
          className="rounded"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/200",
            objectFit: "cover",
          }}
          width="400"
        />
      </div>
    </div>
  )
}
